id: I9AD2EABE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T21:57:39+00:00'
last_modified: '2022-06-09T04:33:11.270695+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG0545
  title: ཀུན་དཔལ་སྤྱོད་འཇུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ABF0:
      image_group_id: I1KG20698
      title: Volume 1 of kun dpal spyod 'jug
      total_pages: 696
      order: 1
      base_file: ABF0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
