id: P008107
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG0545
  title: ཀུན་དཔལ་སྤྱོད་འཇུག
  author: ''
  volumes:
    7f67991f9a654aa1ad3074d3613564b6:
      image_group_id: I1KG20698
      title: ''
      volume_number: 1
      total_pages: 696
ebook_metadata:
  title: ཀུན་དཔལ་སྤྱོད་འཇུག
  author: ''
  sku: P008107
  cover: cover.jpg
  layers:
  - pagination
