id: P008107
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 13:02:03.885959
source_metadata:
  id: bdr:W00KG0545
  title: ཀུན་དཔལ་སྤྱོད་འཇུག
  author: ''
  volumes:
    90bd605c0cb54f18be62e0be6a95cdd6:
      image_group_id: I1KG20698
      title: Volume 1 of kun dpal spyod 'jug
      volume_number: 1
      total_pages: 696
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
